//! Plan + device registry. The set of plans + devices `cirrus-qs` can run.

use cirrus_core::lua_exposable::LuaMethodEntry;
use cirrus_core::msg::{
    CollectableObj, FlyableObj, LocatableObj, MovableObj, ReadableObj, StageableObj, TriggerableObj,
};
use cirrus_core::plan::Plan;
use serde_json::Value;
use std::any::Any;
use std::collections::HashMap;
use std::sync::Arc;

/// One device's `#[lua_methods]` table + a downcast handle.
#[derive(Clone)]
pub struct LuaExposedEntry {
    /// Static method table generated by the proc macro.
    pub methods: &'static [LuaMethodEntry],
    /// `Arc<dyn Any + Send + Sync>` cast of the concrete device, so
    /// the dispatch fns (which take `&dyn Any`) can downcast.
    pub device: Arc<dyn Any + Send + Sync>,
}

/// Plan factory function. Builds a `Plan` from JSON arguments
/// (`{"args": [...], "kwargs": {...}}`).
pub type PlanFactory =
    Arc<dyn Fn(&Registry, &Value) -> Result<Plan, String> + Send + Sync + 'static>;

/// Registered devices, indexed by string name. The same physical device
/// usually appears under more than one trait — register each role explicitly.
///
/// `Clone` is implemented (cheap — every value is an `Arc<dyn ...>`)
/// so callers can share the registry between the `Server` and a
/// daemon-side evaluator that publishes the same devices into a Lua
/// state.
#[derive(Clone, Default)]
pub struct Registry {
    plans: HashMap<String, PlanFactory>,
    readables: HashMap<String, Arc<dyn ReadableObj>>,
    movables: HashMap<String, Arc<dyn MovableObj>>,
    locatables: HashMap<String, Arc<dyn LocatableObj>>,
    triggerables: HashMap<String, Arc<dyn TriggerableObj>>,
    stageables: HashMap<String, Arc<dyn StageableObj>>,
    flyables: HashMap<String, Arc<dyn FlyableObj>>,
    collectables: HashMap<String, Arc<dyn CollectableObj>>,
    /// Devices with `#[lua_methods]`-derived `LuaExposable` impls.
    /// Surfaced through the daemon's Lua state as device-specific
    /// methods on the device global. See cirrus-cli/manager_lua.rs.
    lua_exposed: HashMap<String, LuaExposedEntry>,
}

impl Registry {
    /// Build empty.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a plan factory.
    pub fn register_plan(&mut self, name: impl Into<String>, factory: PlanFactory) {
        self.plans.insert(name.into(), factory);
    }

    /// Register a `ReadableObj` device under a name.
    pub fn register_readable(&mut self, name: impl Into<String>, obj: Arc<dyn ReadableObj>) {
        self.readables.insert(name.into(), obj);
    }

    /// Register a `MovableObj` device.
    pub fn register_movable(&mut self, name: impl Into<String>, obj: Arc<dyn MovableObj>) {
        self.movables.insert(name.into(), obj);
    }

    /// Register a `LocatableObj` device. Locatable extends Movable;
    /// register both for full motor surface (set + locate).
    pub fn register_locatable(&mut self, name: impl Into<String>, obj: Arc<dyn LocatableObj>) {
        self.locatables.insert(name.into(), obj);
    }

    /// Register a `TriggerableObj` device.
    pub fn register_triggerable(&mut self, name: impl Into<String>, obj: Arc<dyn TriggerableObj>) {
        self.triggerables.insert(name.into(), obj);
    }

    /// Register a `StageableObj` device.
    pub fn register_stageable(&mut self, name: impl Into<String>, obj: Arc<dyn StageableObj>) {
        self.stageables.insert(name.into(), obj);
    }

    /// Register a `FlyableObj` device.
    pub fn register_flyable(&mut self, name: impl Into<String>, obj: Arc<dyn FlyableObj>) {
        self.flyables.insert(name.into(), obj);
    }

    /// Register a `CollectableObj` device.
    pub fn register_collectable(&mut self, name: impl Into<String>, obj: Arc<dyn CollectableObj>) {
        self.collectables.insert(name.into(), obj);
    }

    /// Register the device's `#[lua_methods]` table for daemon-Lua
    /// exposure. Devices that implement `cirrus_core::LuaExposable`
    /// (auto-generated by `#[lua_methods]`) call this once after
    /// registering their roles, passing their `Arc<Self>` and
    /// `Self::lua_methods()`.
    pub fn register_lua_methods<T: cirrus_core::LuaExposable + 'static>(
        &mut self,
        name: impl Into<String>,
        device: Arc<T>,
    ) {
        let any: Arc<dyn Any + Send + Sync> = device;
        self.lua_exposed.insert(
            name.into(),
            LuaExposedEntry {
                methods: T::lua_methods(),
                device: any,
            },
        );
    }

    /// Look up a device's lua-exposed entry by name (used by the
    /// daemon-side Lua bridge in cirrus-cli).
    pub fn lua_exposed(&self, name: &str) -> Option<&LuaExposedEntry> {
        self.lua_exposed.get(name)
    }

    /// Look up a `ReadableObj` by name.
    pub fn readable(&self, name: &str) -> Option<&Arc<dyn ReadableObj>> {
        self.readables.get(name)
    }

    /// Look up a `MovableObj` by name.
    pub fn movable(&self, name: &str) -> Option<&Arc<dyn MovableObj>> {
        self.movables.get(name)
    }

    /// Look up a `LocatableObj` by name.
    pub fn locatable(&self, name: &str) -> Option<&Arc<dyn LocatableObj>> {
        self.locatables.get(name)
    }

    /// Look up a `TriggerableObj` by name.
    pub fn triggerable(&self, name: &str) -> Option<&Arc<dyn TriggerableObj>> {
        self.triggerables.get(name)
    }

    /// Look up a `StageableObj` by name.
    pub fn stageable(&self, name: &str) -> Option<&Arc<dyn StageableObj>> {
        self.stageables.get(name)
    }

    /// Look up a `FlyableObj` by name.
    pub fn flyable(&self, name: &str) -> Option<&Arc<dyn FlyableObj>> {
        self.flyables.get(name)
    }

    /// Look up a `CollectableObj` by name.
    pub fn collectable(&self, name: &str) -> Option<&Arc<dyn CollectableObj>> {
        self.collectables.get(name)
    }

    /// Look up a registered plan factory by name.
    pub fn plan(&self, name: &str) -> Option<&PlanFactory> {
        self.plans.get(name)
    }

    /// All plan names.
    pub fn plan_names(&self) -> Vec<String> {
        let mut v: Vec<_> = self.plans.keys().cloned().collect();
        v.sort();
        v
    }

    /// Look up `name` across every role table and return the first
    /// `NamedObj::inspect_dyn` result. The map is sorted-iterated in
    /// the same role order as registration so the result is stable.
    /// `None` if the name is not registered in any role.
    pub fn inspect_device(&self, name: &str) -> Option<serde_json::Value> {
        if let Some(o) = self.readables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.movables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.triggerables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.stageables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.flyables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.collectables.get(name) {
            return Some(o.inspect_dyn());
        }
        None
    }

    /// All device names (union over all role registrations + lua-only
    /// devices). A device registered solely via
    /// `register_lua_methods` (no readable/movable/...) still appears
    /// here so the daemon Lua state publishes it as a global.
    pub fn device_names(&self) -> Vec<String> {
        let mut s = std::collections::BTreeSet::new();
        for k in self.readables.keys() {
            s.insert(k.clone());
        }
        for k in self.movables.keys() {
            s.insert(k.clone());
        }
        for k in self.locatables.keys() {
            s.insert(k.clone());
        }
        for k in self.triggerables.keys() {
            s.insert(k.clone());
        }
        for k in self.stageables.keys() {
            s.insert(k.clone());
        }
        for k in self.flyables.keys() {
            s.insert(k.clone());
        }
        for k in self.collectables.keys() {
            s.insert(k.clone());
        }
        for k in self.lua_exposed.keys() {
            s.insert(k.clone());
        }
        s.into_iter().collect()
    }

    /// Convenience: register the canonical `count` plan (`count(detectors, num)`).
    /// Args shape: `{"args": ["det1", "det2", ...], "kwargs": {"num": 5}}`
    /// or `{"args": [["det1", "det2"], 5]}`.
    pub fn register_plan_count(&mut self, name: impl Into<String>) {
        let factory: PlanFactory = Arc::new(|reg, args| {
            let (dets_raw, num) = parse_count_args(args)?;
            let mut dets: Vec<Arc<dyn ReadableObj>> = Vec::with_capacity(dets_raw.len());
            for d in &dets_raw {
                let obj = reg
                    .readable(d)
                    .ok_or_else(|| format!("unknown detector: {d}"))?
                    .clone();
                dets.push(obj);
            }
            Ok(cirrus_plans::count(dets, num))
        });
        self.register_plan(name, factory);
    }
}

fn parse_count_args(args: &Value) -> Result<(Vec<String>, usize), String> {
    // Accept both kwargs- and positional-style.
    if let Some(obj) = args.as_object() {
        let detectors = obj
            .get("args")
            .and_then(|a| a.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|v| v.as_str().map(|s| s.to_string()))
                    .collect::<Vec<_>>()
            })
            .or_else(|| {
                obj.get("kwargs")
                    .and_then(|k| k.get("detectors"))
                    .and_then(|d| d.as_array())
                    .map(|a| {
                        a.iter()
                            .filter_map(|v| v.as_str().map(|s| s.to_string()))
                            .collect::<Vec<_>>()
                    })
            })
            .unwrap_or_default();
        let num = obj
            .get("kwargs")
            .and_then(|k| k.get("num"))
            .and_then(|n| n.as_u64())
            .or_else(|| {
                obj.get("args")
                    .and_then(|a| a.as_array())
                    .and_then(|a| a.last())
                    .and_then(|v| v.as_u64())
            })
            .ok_or_else(|| "count: missing 'num' argument".to_string())? as usize;
        Ok((detectors, num))
    } else {
        Err(format!("count args must be object; got {args}"))
    }
}
